site_name: Data Beauty Kami
site_author: Guilherme Nazareth
site_url: analytickamico.gitlab.io/databeauty
site_description: >-
  Site com a documentação de referência do data baeuty, manual dos dashs
  e regras de negócio, dos  dados disponibilizados pela Kami CO.

copyright: Copyright &copy; 2024 Kami CO
nav:
  - Home: index.md
theme:
  name: material
